apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: add-pet
spec:
  serviceAccountName: runner
  entrypoint: main
  arguments:
    parameters:
    - name: url
      valueFrom:
        configMapKeyRef:
          name: params
          key: base-url
  templates:
    - name: main
      # inputs:

      steps:
        - - name: generate-pet-id
            templateRef:
              name: common
              template: random-int
        - - name: add-pet
            templateRef:
              name: petstore
              template: http-add-pet
            arguments:
              parameters:
                - name: path
                  value: "/api/v3/pet"
                - name: petId
                  value: "{{steps.generate-pet-id.outputs.result}}"
        - - name: debug
            templateRef:
              name: common
              template: print-message
            arguments:
              parameters:
              - name: message
                value: "{{steps.add-pet.outputs.result}}"
        - - name: extract-pet-id
            templateRef:
              name: common
              template: jq
            arguments:
              parameters:
                - name: json
                  value: "{{steps.add-pet.outputs.result}}"

        - - name: get-pet
            # template: http-get-pet
            templateRef:
              name: petstore
              template: http-get-pet
            arguments:
              parameters:
                - name: path
                  value: "/api/v3/pet"
                - name: id
                  value: "{{steps.extract-pet-id.outputs.result}}"
