apiVersion: v1
kind: ConfigMap
metadata:
  name: params
  namespace: argo
  labels:
    # This label is required for the informer to detect this ConfigMap
    workflows.argoproj.io/configmap-type: Parameter
data:
  base-url: http://petstore.dev.me:1880
  welcome-msg: |
    Welome to my petstore!
    Enjoy your stay!