apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: add-pet
spec:
  serviceAccountName: runner
  entrypoint: main
  # TODO: this does not work for templates, only for workflows
  arguments:
    parameters:
    - name: url
      valueFrom:
        configMapKeyRef:
          name: params
          key: base-url
  templates:
    - name: main
      # inputs:

      steps:
        - - name: debug-base-url
            templateRef:
              name: common
              template: print-message
            arguments:
              parameters:
              - name: message
                value: "{{workflow.parameters.url}}"
        - - name: generate-pet-id
            templateRef:
              name: common
              template: random-int
        - - name: add-pet
            templateRef:
              name: petstore
              template: http-add-pet
            arguments:
              parameters:
                - name: path
                  value: "/api/v3/pet"
                - name: petId
                  value: "{{steps.generate-pet-id.outputs.result}}"
        - - name: get-pet
            templateRef:
              name: petstore
              template: http-get-pet
            arguments:
              parameters:
                - name: path
                  value: "/api/v3/pet"
                - name: id
                  value: "{{=jsonpath(steps['add-pet'].outputs.result, '$.id')}}"