apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-runner
  annotations:
    workflows.argoproj.io/description: |
      This is the minimum recommended permissions needed if you want to use the agent, e.g. for HTTP or plugin templates.
      If <= v3.2 you must replace `workflowtasksets/status` with `patch workflowtasksets`.
rules:
  # https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/
  # The minimum for the executor to function:
  # For >= v3.4:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
  # Required else RBAC errors in agent pods 
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
    verbs:
      # - list
      - watch
  # needed for argo-role else status of HTTP tasks cannot be updated correctly by workflow controller
  # Agent pods when using HTTP templates
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
    verbs:
      - patch
  # - apiGroups:
  #     - ""
  #   resources:
  #     - pods
  #     - pods/exec
  #   verbs:
  #     - create
  #     - get
  #     - list
  #     - watch
  #     - update
  #     - patch
  #     - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-runner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-runner
subjects:
- kind: ServiceAccount
  name: workflow-runner
  # namespace: default
---
# https://argo-workflows.readthedocs.io/en/latest/service-account-secrets/
apiVersion: v1
kind: Secret
metadata:
  name: workflow-runner.service-account-token
  annotations:
    kubernetes.io/service-account.name: workflow-runner
type: kubernetes.io/service-account-token